language: ruby
cache: bundler

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0

script: "bundle exec rake"

notifications:
  email:
    recipients:
      - subjectego@gmail.com
    on_failure: change
    on_success: never
